services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    # depends_on:
    #   - elasticsearch
    networks:
      - elastic
    environment:
      - NODE_ENV=development

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
  #   container_name: es01
  #   environment:
  #     - node.name=es01
  #     - cluster.name=elastic-cluster
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - xpack.security.http.ssl.enabled=false
  #     - path.repo=/usr/share/elasticsearch/backup
  #   # volumes:
  #   #   - esdata:/usr/share/elasticsearch/data
  #   #   - ./shared-backup:/usr/share/elasticsearch/backup
  #   ports:
  #     - "9200:9200"
  #   networks:
  #     - elastic

  # kibana:
  # image: docker.elastic.co/kibana/kibana:9.0.0
  # container_name: kib01
  # # depends_on:
  # #   - elasticsearch
  # environment:
  #   - SERVER_NAME=kibana
  #   - ELASTICSEARCH_HOSTS=https://elastic.dev.bbext.digital
  #   # - ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL3Rva2VuXy1TT2hVcFlCSmNZZXh1Ylh5cmZNOlFUUWIxRFhiVEJpby1fR2lTVVZmZ3c
  # ports:
  #   - "5601:5601"
  # networks:
  #   - elastic

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.0.0
    container_name: filebeat
    user: root
    command: filebeat -e --strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs:ro # Your application logs
      - ./filebeat-registry:/usr/share/filebeat/data # Persist registry state
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elastic

volumes:
  esdata:

networks:
  elastic:
    driver: bridge
