filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /logs/*.log
    fields:
      log_type: express-app
    fields_under_root: true
    processors:
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

filebeat.modules:
  - module: system
    syslog:
      enabled: true
    auth:
      enabled: true

output.elasticsearch:
  hosts: ["https://elastic.dev.bbext.digital:443"]
  username: "dev"
  password: "i05s0UtH5CC87eF1n48Zl0HL"
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.kibana:
  host: "https://kibana.dev.bbext.digital"

logging.level: info
